import { cloudCall } from '@/composables/useCloudCall'
import type { BusinessCollectionName, OutboxMutation, SyncMetadata } from '@/localdb/types'

export const LOCAL_MUTATION_TYPES = {
  CREATE_HEALTH_RECORDS: 'health.batchAddHealthRecords',
  CREATE_MEDICATION_TASKS: 'health.batchStartMedication',
  UPDATE_HEALTH_RECORD: 'health.updateHealthRecord',
  DELETE_HEALTH_RECORD: 'health.deleteHealthRecord',
  CREATE_BREEDING_RECORD: 'breeding.addBreedingRecord',
  BATCH_CREATE_BREEDING_RECORDS: 'breeding.batchAddBreedingRecords',
  ADD_BIRTH_RECORD: 'breeding.addBirthRecord',
  UPDATE_BREEDING_RECORD: 'breeding.updateBreedingRecord',
  DELETE_BREEDING_RECORD: 'breeding.deleteBreedingRecord',
  CLOSE_BREEDING_CYCLE: 'breeding.closeCycle',
  ADD_PUPPY_TO_LITTER: 'breeding.addPuppyToLitter',
  UPDATE_LITTER: 'breeding.updateLitter',
  UPDATE_LITTER_BIRTH_DATE: 'breeding.updateBirthDate',
  CONFIRM_WEANING: 'breeding.confirmWeaning',
  CREATE_EXPENSE: 'finance.addExpense',
  CREATE_INCOME: 'finance.addIncome',
  UPDATE_EXPENSE: 'finance.updateExpense',
  UPDATE_INCOME: 'finance.updateIncome',
  DELETE_EXPENSE: 'finance.deleteExpense',
  DELETE_INCOME: 'finance.deleteIncome',
  CREATE_SALE_RECORD: 'finance.createSaleRecord',
  RECEIVE_SALE_DEPOSIT: 'finance.receiveSaleDeposit',
  COMPLETE_SALE: 'finance.completeSale',
  SETTLE_SALE: 'finance.settleSale',
  CANCEL_SALE: 'finance.cancelSale',
  CREATE_AGENT: 'finance.addAgent',
  UPDATE_AGENT: 'finance.updateAgent',
  REMOVE_AGENT: 'finance.removeAgent',
  UPDATE_FAMILY_SETTINGS: 'family.updateSettings',
  ADD_CARE_RULE: 'family.addCareRule',
  REMOVE_CARE_RULE: 'family.removeCareRule',
  UPDATE_NICKNAME: 'family.updateNickname',
  ADD_EXPENSE_CATEGORY_GROUP: 'finance.addExpenseCategoryGroup',
  UPDATE_EXPENSE_CATEGORY_GROUP: 'finance.updateExpenseCategoryGroup',
  REMOVE_EXPENSE_CATEGORY_GROUP: 'finance.removeExpenseCategoryGroup',
  ADD_EXPENSE_CATEGORY: 'finance.addExpenseCategory',
  UPDATE_EXPENSE_CATEGORY: 'finance.updateExpenseCategory',
  REMOVE_EXPENSE_CATEGORY: 'finance.removeExpenseCategory',
  ADD_MEDICATION_PROTOCOL: 'health.addMedicationProtocol',
  REMOVE_MEDICATION_PROTOCOL: 'health.removeMedicationProtocol',
  BATCH_CREATE_TASKS: 'task.batchCreateManualTasks',
  CREATE_DOG: 'dog.create',
  UPDATE_DOG: 'dog.update',
  UPDATE_DOG_NAME: 'dog.updateName',
  CHANGE_DOG_DISPOSITION: 'dog.changeDisposition',
  UPGRADE_PUPPY_TO_BREEDER: 'dog.upgradePuppyToBreeder',
  SOFT_DELETE_DOG: 'dog.softDelete',
  RESTORE_DOG: 'dog.restore',
  RECYCLE_RESTORE: 'recycle.restore',
  RECYCLE_PERMANENT_DELETE: 'recycle.permanentDelete',
  COMPLETE_TASK: 'task.complete',
  BATCH_COMPLETE_TASK: 'task.batchComplete',
  POSTPONE_TASK: 'task.postpone',
  BATCH_POSTPONE_TASK: 'task.batchPostpone',
  RECORD_MEDICATION_DOSE: 'health.recordMedicationDose',
  BATCH_COMPLETE_MEDICATION_DAY: 'health.batchCompleteMedicationDay',
  END_MEDICATION: 'health.endMedication',
  RECOVER_ILLNESSES: 'health.recoverIllnesses',
  UPDATE_ILLNESS_STATUS: 'health.batchUpdateIllnessStatus',
  END_MEDICATION_BY_DOG: 'health.endMedicationByDog',
  ADD_DOG_WEIGHT: 'health.addWeightRecord',
} as const

export type LocalMutationType = typeof LOCAL_MUTATION_TYPES[keyof typeof LOCAL_MUTATION_TYPES]
export type LocalMutationPayload = Record<string, any>

export interface LocalMutationDefinition {
  service: string
  method: string
  defaultScopes: BusinessCollectionName[]
}

export const LOCAL_MUTATION_REGISTRY: Record<LocalMutationType, LocalMutationDefinition> = {
  [LOCAL_MUTATION_TYPES.CREATE_HEALTH_RECORDS]: { service: 'health-service', method: 'batchAddHealthRecords', defaultScopes: ['health_records', 'tasks', 'expenses'] },
  [LOCAL_MUTATION_TYPES.CREATE_MEDICATION_TASKS]: { service: 'health-service', method: 'batchStartMedication', defaultScopes: ['medication_tasks', 'health_records', 'expenses'] },
  [LOCAL_MUTATION_TYPES.UPDATE_HEALTH_RECORD]: { service: 'health-service', method: 'updateHealthRecord', defaultScopes: ['health_records', 'expenses'] },
  [LOCAL_MUTATION_TYPES.DELETE_HEALTH_RECORD]: { service: 'health-service', method: 'deleteHealthRecord', defaultScopes: ['health_records', 'tasks', 'expenses'] },
  [LOCAL_MUTATION_TYPES.CREATE_BREEDING_RECORD]: { service: 'breeding-service', method: 'addBreedingRecord', defaultScopes: ['breeding_records', 'breeding_cycles', 'tasks', 'expenses', 'litters'] },
  [LOCAL_MUTATION_TYPES.BATCH_CREATE_BREEDING_RECORDS]: { service: 'breeding-service', method: 'batchAddBreedingRecords', defaultScopes: ['breeding_records', 'breeding_cycles', 'tasks'] },
  [LOCAL_MUTATION_TYPES.ADD_BIRTH_RECORD]: { service: 'breeding-service', method: 'addBirthRecord', defaultScopes: ['breeding_records', 'breeding_cycles', 'litters', 'dogs', 'dog_weights', 'tasks', 'expenses'] },
  [LOCAL_MUTATION_TYPES.UPDATE_BREEDING_RECORD]: { service: 'breeding-service', method: 'updateBreedingRecord', defaultScopes: ['breeding_records', 'tasks', 'expenses'] },
  [LOCAL_MUTATION_TYPES.DELETE_BREEDING_RECORD]: { service: 'breeding-service', method: 'deleteBreedingRecord', defaultScopes: ['breeding_records', 'tasks', 'expenses'] },
  [LOCAL_MUTATION_TYPES.CLOSE_BREEDING_CYCLE]: { service: 'breeding-service', method: 'closeCycle', defaultScopes: ['breeding_cycles', 'tasks'] },
  [LOCAL_MUTATION_TYPES.ADD_PUPPY_TO_LITTER]: { service: 'breeding-service', method: 'addPuppyToLitter', defaultScopes: ['dogs', 'litters'] },
  [LOCAL_MUTATION_TYPES.UPDATE_LITTER]: { service: 'breeding-service', method: 'updateLitter', defaultScopes: ['litters'] },
  [LOCAL_MUTATION_TYPES.UPDATE_LITTER_BIRTH_DATE]: { service: 'breeding-service', method: 'updateBirthDate', defaultScopes: ['litters', 'dogs', 'expenses'] },
  [LOCAL_MUTATION_TYPES.CONFIRM_WEANING]: { service: 'breeding-service', method: 'confirmWeaning', defaultScopes: ['litters', 'tasks'] },
  [LOCAL_MUTATION_TYPES.CREATE_EXPENSE]: { service: 'finance-service', method: 'addExpense', defaultScopes: ['expenses'] },
  [LOCAL_MUTATION_TYPES.CREATE_INCOME]: { service: 'finance-service', method: 'addIncome', defaultScopes: ['incomes'] },
  [LOCAL_MUTATION_TYPES.UPDATE_EXPENSE]: { service: 'finance-service', method: 'updateExpense', defaultScopes: ['expenses'] },
  [LOCAL_MUTATION_TYPES.UPDATE_INCOME]: { service: 'finance-service', method: 'updateIncome', defaultScopes: ['incomes'] },
  [LOCAL_MUTATION_TYPES.DELETE_EXPENSE]: { service: 'finance-service', method: 'deleteExpense', defaultScopes: ['expenses'] },
  [LOCAL_MUTATION_TYPES.DELETE_INCOME]: { service: 'finance-service', method: 'deleteIncome', defaultScopes: ['incomes'] },
  [LOCAL_MUTATION_TYPES.CREATE_SALE_RECORD]: { service: 'finance-service', method: 'createSaleRecord', defaultScopes: ['sale_records', 'dogs'] },
  [LOCAL_MUTATION_TYPES.RECEIVE_SALE_DEPOSIT]: { service: 'finance-service', method: 'receiveSaleDeposit', defaultScopes: ['sale_records', 'dogs'] },
  [LOCAL_MUTATION_TYPES.COMPLETE_SALE]: { service: 'finance-service', method: 'completeSale', defaultScopes: ['sale_records', 'dogs', 'incomes'] },
  [LOCAL_MUTATION_TYPES.SETTLE_SALE]: { service: 'finance-service', method: 'settleSale', defaultScopes: ['sale_records', 'incomes'] },
  [LOCAL_MUTATION_TYPES.CANCEL_SALE]: { service: 'finance-service', method: 'cancelSale', defaultScopes: ['sale_records', 'dogs', 'incomes'] },
  [LOCAL_MUTATION_TYPES.CREATE_AGENT]: { service: 'finance-service', method: 'addAgent', defaultScopes: ['agents'] },
  [LOCAL_MUTATION_TYPES.UPDATE_AGENT]: { service: 'finance-service', method: 'updateAgent', defaultScopes: ['agents'] },
  [LOCAL_MUTATION_TYPES.REMOVE_AGENT]: { service: 'finance-service', method: 'removeAgent', defaultScopes: ['agents'] },
  [LOCAL_MUTATION_TYPES.UPDATE_FAMILY_SETTINGS]: { service: 'family-service', method: 'updateSettings', defaultScopes: ['families'] },
  [LOCAL_MUTATION_TYPES.ADD_CARE_RULE]: { service: 'family-service', method: 'addCareRule', defaultScopes: ['families'] },
  [LOCAL_MUTATION_TYPES.REMOVE_CARE_RULE]: { service: 'family-service', method: 'removeCareRule', defaultScopes: ['families'] },
  [LOCAL_MUTATION_TYPES.UPDATE_NICKNAME]: { service: 'family-service', method: 'updateNickname', defaultScopes: ['families'] },
  [LOCAL_MUTATION_TYPES.ADD_EXPENSE_CATEGORY_GROUP]: { service: 'finance-service', method: 'addExpenseCategoryGroup', defaultScopes: ['families'] },
  [LOCAL_MUTATION_TYPES.UPDATE_EXPENSE_CATEGORY_GROUP]: { service: 'finance-service', method: 'updateExpenseCategoryGroup', defaultScopes: ['families'] },
  [LOCAL_MUTATION_TYPES.REMOVE_EXPENSE_CATEGORY_GROUP]: { service: 'finance-service', method: 'removeExpenseCategoryGroup', defaultScopes: ['families'] },
  [LOCAL_MUTATION_TYPES.ADD_EXPENSE_CATEGORY]: { service: 'finance-service', method: 'addExpenseCategory', defaultScopes: ['families'] },
  [LOCAL_MUTATION_TYPES.UPDATE_EXPENSE_CATEGORY]: { service: 'finance-service', method: 'updateExpenseCategory', defaultScopes: ['families', 'expenses'] },
  [LOCAL_MUTATION_TYPES.REMOVE_EXPENSE_CATEGORY]: { service: 'finance-service', method: 'removeExpenseCategory', defaultScopes: ['families'] },
  [LOCAL_MUTATION_TYPES.ADD_MEDICATION_PROTOCOL]: { service: 'health-service', method: 'addMedicationProtocol', defaultScopes: ['medication_protocols'] },
  [LOCAL_MUTATION_TYPES.REMOVE_MEDICATION_PROTOCOL]: { service: 'health-service', method: 'removeMedicationProtocol', defaultScopes: ['medication_protocols'] },
  [LOCAL_MUTATION_TYPES.BATCH_CREATE_TASKS]: { service: 'task-service', method: 'batchCreateManualTasks', defaultScopes: ['tasks'] },
  [LOCAL_MUTATION_TYPES.CREATE_DOG]: { service: 'dog-service', method: 'createDog', defaultScopes: ['dogs', 'expenses'] },
  [LOCAL_MUTATION_TYPES.UPDATE_DOG]: { service: 'dog-service', method: 'updateDog', defaultScopes: ['dogs'] },
  [LOCAL_MUTATION_TYPES.UPDATE_DOG_NAME]: { service: 'dog-service', method: 'updateDogName', defaultScopes: ['dogs', 'tasks', 'breeding_cycles', 'litters'] },
  [LOCAL_MUTATION_TYPES.CHANGE_DOG_DISPOSITION]: { service: 'dog-service', method: 'changeDisposition', defaultScopes: ['dogs', 'breeding_cycles', 'tasks', 'incomes'] },
  [LOCAL_MUTATION_TYPES.UPGRADE_PUPPY_TO_BREEDER]: { service: 'dog-service', method: 'upgradePuppyToBreeder', defaultScopes: ['dogs'] },
  [LOCAL_MUTATION_TYPES.SOFT_DELETE_DOG]: { service: 'dog-service', method: 'softDeleteDog', defaultScopes: ['dogs'] },
  [LOCAL_MUTATION_TYPES.RESTORE_DOG]: { service: 'dog-service', method: 'restoreDog', defaultScopes: ['dogs'] },
  [LOCAL_MUTATION_TYPES.RECYCLE_RESTORE]: { service: 'family-service', method: 'restoreItem', defaultScopes: ['dogs', 'expenses', 'incomes', 'agents', 'medication_protocols'] },
  [LOCAL_MUTATION_TYPES.RECYCLE_PERMANENT_DELETE]: { service: 'family-service', method: 'permanentDeleteItem', defaultScopes: ['dogs', 'expenses', 'incomes', 'agents', 'medication_protocols'] },
  [LOCAL_MUTATION_TYPES.COMPLETE_TASK]: { service: 'task-service', method: 'completeTask', defaultScopes: ['tasks', 'health_records'] },
  [LOCAL_MUTATION_TYPES.BATCH_COMPLETE_TASK]: { service: 'task-service', method: 'batchCompleteTask', defaultScopes: ['tasks', 'health_records'] },
  [LOCAL_MUTATION_TYPES.POSTPONE_TASK]: { service: 'task-service', method: 'postponeTask', defaultScopes: ['tasks'] },
  [LOCAL_MUTATION_TYPES.BATCH_POSTPONE_TASK]: { service: 'task-service', method: 'batchPostponeTask', defaultScopes: ['tasks'] },
  [LOCAL_MUTATION_TYPES.RECORD_MEDICATION_DOSE]: { service: 'health-service', method: 'recordMedicationDose', defaultScopes: ['medication_tasks'] },
  [LOCAL_MUTATION_TYPES.BATCH_COMPLETE_MEDICATION_DAY]: { service: 'health-service', method: 'batchCompleteMedicationDay', defaultScopes: ['medication_tasks'] },
  [LOCAL_MUTATION_TYPES.END_MEDICATION]: { service: 'health-service', method: 'endMedication', defaultScopes: ['medication_tasks', 'health_records', 'tasks'] },
  [LOCAL_MUTATION_TYPES.RECOVER_ILLNESSES]: { service: 'health-service', method: 'recoverIllnesses', defaultScopes: ['health_records', 'medication_tasks'] },
  [LOCAL_MUTATION_TYPES.UPDATE_ILLNESS_STATUS]: { service: 'health-service', method: 'batchUpdateIllnessStatus', defaultScopes: ['health_records'] },
  [LOCAL_MUTATION_TYPES.END_MEDICATION_BY_DOG]: { service: 'health-service', method: 'endMedicationByDog', defaultScopes: ['medication_tasks'] },
  [LOCAL_MUTATION_TYPES.ADD_DOG_WEIGHT]: { service: 'health-service', method: 'addWeightRecord', defaultScopes: ['dog_weights', 'dogs'] },
}

export function buildSyncPayload<T extends LocalMutationPayload>(payload: T, syncMeta: SyncMetadata): T & { _sync: SyncMetadata } {
  return { ...payload, _sync: syncMeta }
}

export async function dispatchRegisteredMutation(mutation: OutboxMutation<LocalMutationPayload>) {
  const definition = LOCAL_MUTATION_REGISTRY[mutation.type as LocalMutationType]
  if (!definition) throw new Error(`未知 mutation 类型: ${mutation.type}`)
  return cloudCall(definition.service, definition.method, mutation.payload)
}
